### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by SebaMat3** [ferneynava/Nuevo-Curso-de-ECMAScript-#1]
Hi comrade! I'm from Platzi. Thanks for sharing you notes, much appreciated!

There's a little typo in the  Introducción chapter:
- where you're speaking about ARPANET, it says ARPADET.

"1969: Se creo la red ARPADET una forma de comunicar dos computadoras, para compartir información."

Good luck!

**Comment by ferneynava** [comment]
¡Muchas gracias por tu contribución a mejorar las notas de este curso! Error tipográfico solucionado.
